### ISSUE TITLE
Link issues with sobjectizer

### ISSUE THREAD

**Issue by zamazan4ik** [Stiffstream/sobjectizer-conan#1]
Hi!

I try to use `sobjectizer` library from Conan (`sobjectizer/5.7.0@stiffstream/stable`).

I try to build this source file: https://github.com/Stiffstream/restinio/blob/master/dev/sample/async_handling_with_sobjectizer/main.cpp

Required libraries are downloaded and linked with the following piece of CMake code:
```
project(Example)

set(CMAKE_CXX_STANDARD 17)

# Download automatically, you can also just copy the conan.cmake file
if(NOT EXISTS "${CMAKE_BINARY_DIR}/conan.cmake")
    message(STATUS "Downloading conan.cmake from https://github.com/conan-io/cmake-conan")
    file(DOWNLOAD "https://github.com/conan-io/cmake-conan/raw/v0.15/conan.cmake"
            "${CMAKE_BINARY_DIR}/conan.cmake")
endif()

include(${CMAKE_BINARY_DIR}/conan.cmake)

conan_cmake_run(REQUIRES
        jsonformoderncpp/3.6.1@vthiery/stable
        restinio/0.6.5@stiffstream/stable
        sobjectizer/5.6.2@stiffstream/stable
        OPTIONS sobjectizer:shared=False
        BASIC_SETUP
        CMAKE_TARGETS
        BUILD missing)

set(SRC
        main.cpp
)

add_executable(Example ${SRC})
target_link_libraries(Example Common CONAN_PKG::restinio CONAN_PKG::sobjectizer CONAN_PKG::jsonformoderncpp)
```

But during build I've got the following errors: https://pastebin.com/LNGWakU2

So you see some link errors for symbols which shall be accessible (I've checked sobjectizer source code - at least for my eyes all is fine with symbols).

I've ran compiler with `-v` and got the following output: https://pastebin.com/f9pjjvTZ

Conan recipe as an output for static Sobjectizer build have a library with name `libso_s.5.7.0.a`. And in detailed compiler report I cannot find such name - so library for some reasons are not linked. I am not a CMake expert but I think that's because library is not exported propeeeeeerly or something like that.

So my question is: how to fix it? If you need any additional info - just ping me here and I'll try to help.

Some details:
* I've tried Clang 9 and GCC 9 - same errors.
* Also I've tried `sobjectizer/5.6.2@stiffstream/stable` - same errors.
* Tried `conan_cmake_run`'s `BASIC` mode (with linking to `${CONAN_LIBS}`) - same errors.

Environment details:
* OS: Fedora 31.
* Conan version: 1.23

**Comment by zamazan4ik** [comment]
I am not sure is it related to the issue or not, but I've enabled locally some hook from conan, and during dependency installation from Conan have the following warns:
```
[HOOK - conan-center.py] post_package_info(): ERROR: [CMAKE FILE NOT IN BUILD FOLDERS (KB-H019)] The *.cmake files have to be placed in a folder declared as `cpp_info.builddirs`. Currently folders declared: [''] (https://github.com/conan-io/conan-center-index/wiki/Error-Knowledge-Base#KB-H019)
[HOOK - conan-center.py] post_package_info(): ERROR: [CMAKE FILE NOT IN BUILD FOLDERS (KB-H019)] Found files:
./lib/cmake/sobjectizer/sobjectizer-config.cmake
./lib/cmake/sobjectizer/sobjectizer-targets.cmake
./lib/cmake/sobjectizer/sobjectizer-config-version.cmake
./lib/cmake/sobjectizer/sobjectizer-targets-debug.cmake (https://github.com/conan-io/conan-center-index/wiki/Error-Knowledge-Base#KB-H019)
```

**Comment by eao197** [comment]
I've updated conan recipes for SObjectizer-5.6.2 and SObjectizer-5.7.0 in stiffstream/public repository.

**Comment by zamazan4ik** [comment]
I didn't test older versions. Possibly they are also affected.
